#!/bin/bash

while getopts d:i: flag; do
    case "${flag}" in
        i)
            light -A "${OPTARG}%"
            break
            ;;
        d)
            light -U "${OPTARG}%"
            break
            ;;
    esac
done

percent=$(light -G|cut -d. -f1)
dunstify -h int:value:"$percent" -h string:x-canonical-private-synchronous:light "Brightness: ${percent}%" --timeout 1000
