#!/bin/sh

export MAIN_RATIO="0.55"
export MOZ_ENABLE_WAYLAND=1

riverctl border-color-focused 0x0cf7e8
riverctl border-color-unfocused 0xa3b3bb

luajit $HOME/.config/river/init.lua
exec rivertile -main-ratio $MAIN_RATIO
