#!/bin/sh

#LOCK=""
#QUIT=""
#SHUTDOWN=""
#SUSPEND=""
#HIBERNATE=""
#RESTART=""


LOCK=" Lock"
QUIT=" Quit"
SHUTDOWN=" Shutdown"
SUSPEND=" Suspend"
HIBERNATE=" Hibernate"
RESTART=" Restart"

ACTION=$(echo -e "$LOCK
$QUIT
$SUSPEND
$HIBERNATE
$SHUTDOWN
$RESTART"|wofi --conf "$HOME/.config/wofi/config_alt" --show dmenu)

echo $ACTION

function lock() {
    if [ -f /tmp/current_wallpaper ]; then
        swaylock -s fill -i /tmp/current_wallpaper
    else
        swaylock -c 000000
    fi
}

if [ "$ACTION" == $QUIT ]; then
    if [ ! -z $(pidof Hyprland) ]; then
        hyprctl dispatch exit 0
    elif [ ! -z $(pidof river) ]; then
        riverctl exit
    else
        echo "Fuck off...!!!"
    fi
elif [ "$ACTION" == "$LOCK" ]; then
    lock
elif [ "$ACTION" == "$SUSPEND" ]; then
    lock && systemctl suspend
elif [ "$ACTION" == "$HIBERNATE" ]; then
    lock && systemctl suspend-then-hibernate
elif [ "$ACTION" == "$RESTART" ]; then
    systemctl reboot
elif [ "$ACTION" == "$SHUTDOWN" ]; then
    systemctl poweroff
fi
