#!/bin/bash

while getopts d:i:m: flag; do
    case "${flag}" in
        d)
            pactl set-sink-volume @DEFAULT_SINK@ "-${OPTARG}%"
            break
            ;;
        i)
            pactl set-sink-volume @DEFAULT_SINK@ "+${OPTARG}%"
            break
            ;;
        m)
            pactl set-sink-mute @DEFAULT_SINK@ toggle
            if [ "$(pamixer --get-volume-human)" == "muted" ]; then
                dunstify -h string:x-canonical-private-synchronous:audio "Volume: " "$(pamixer --get-volume-human)"
                exit 0
            fi
            ;;
    esac
done

dunstify -h int:value:`pamixer --get-volume-human` -h string:x-canonical-private-synchronous:audio "Volume: " --timeout 500
